### PR TITLE
Scryfall links/popups

### LINKED ISSUE #94: bans: link cards to scryfall instead deckbox
I think it's just the better site and displays the relevant information (also more) about a card better.

Nobody really wants to add banned cards to their collection or trade them.
Also, their card text is wrong, as they still not support `Energy` correctly...

### PR DESCRIPTION
**Pull request by NilsEnevoldsen**
Fixes #94

### CODE REVIEW

File: js/cardpopup.js [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+				if ( data.layout === 'planar' ) { rotationClass = 'rotate-90cw'; }
+				return data.image_uris.normal;
+			} )
+			.then( imageURI => fetch( imageURI ) )
+			.then( response => response.blob() )
+			.then( blob => {
+				const url = URL.createObjectURL( blob ),
+					img = document.createElement( 'img' );
+				img.classList.add( 'cardimage' );
+				img.classList.add( rotationClass );
```
Comment (glacials) [inline js/cardpopup.js]: `classList.add` takes `String [, String [, ...]] ` as arguments, so these two calls can be collapsed into one.

File: package.json [hunk 2]
```diff
@@ -40,6 +40,7 @@
     "npm-font-open-sans": "^1.1.0",
     "popper.js": "^1.14.3",
     "sw-precache": "^5.2.1",
+    "tippy.js": "^2.6.0",
```
Comment (glacials) [inline package.json]: We're already using `vue-tippy`, is there a way we can reuse that instead of having two separate tippys included?

File: js/cardpopup.js [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+			.then( response => {
+				if ( !response.ok ) { throw Error( response.statusText ); }
+				{ return response; }
+			} )
+			.then( response => response.json() )
+			.then( data => {
+				const queryURI = new URL( target.href ),
+					directURI = new URL( data.scryfall_uri ),
+					utmSource = queryURI.searchParams.get( 'utm_source' );
+				directURI.searchParams.set( 'utm_source', utmSource );
```
[the remark this answers is not in the document]
Comment (NilsEnevoldsen) [reply js/cardpopup.js]: It's not a written policy. @csuhta requests this on an individual basis.

File: js/cardpopup.js (hunk 1 above)
Comment (NilsEnevoldsen) [reply js/cardpopup.js]: Done.

File: service-worker.js [hunk 4]
```diff
@@ -37,7 +37,7 @@
...
...-radio/form-radio-group.js","f5c12d0d4c97a7e7064edb8568a7c5b0"],["node_modules/bootstrap-vue/src/components/form-radio/form-radio.js","8b22fee9097f68419d15bae4f3b6e08e"],["node_modules/bootstrap-vue/src/components/form-radio/form-radio.spec.js","0331c4c6670e2e99a14a307f58ddde5f"],["node_modules/bootstrap-vue/src/components/form-radio/index.js","ef484c7fd2ca4d1a445d30f2a653130e"],["node_modules/bootstrap-vue/src/components/form-radio/package.json","bebb2e4e9bb42e20e944bca832178451"],["node_modules/bootstrap-vue/src/components/form-select/README.md","b38a43693d78c00501ffe8a7d08c71af"],["node_modules/bootstrap-vue/src/components/form-select/fixtures/form-select.html","c600bd7f15d44cd129d70d52c0a2743a"],["node_modules/bootstrap-vue/src/components/form-select/fixtures/form-select.js","e99d578bbe79d7e1e039ea2df150119a"],["node_modules/bootstrap-vue/src/components/form-select/form-select.js","e8c815cc4929f8cba602b355afb3630b"],["node_modules/bootstrap-vue/src/components/form-select/form-select.spec.js","7569064865adfc10e054e38ef0a40a49"],["node_modules/bootstrap-vue/src/components/form-select/index.js","0a1267c006cdcbfb83c08096d528a992"],["node_modules/bootstrap-vue/src/components/form-se
```
[the remark this answers is not in the document]
Comment (NilsEnevoldsen) [reply service-worker.js]: Done.

File: js/cardpopup.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (csuhta) [reply js/cardpopup.js]: Hey there: I'm a member of the @Scryfall team. Please set `utm_source=whatsinstandard` for any traffic you send our way please. ❤️

File: package.json (hunk 2 above)
Comment (NilsEnevoldsen) [reply package.json]: Yeah, I'll wrestle with it until I figure out how it works.

File: js/cardpopup.js (hunk 3 above)
[the remark this answers is not in the document]
Comment (NilsEnevoldsen) [reply js/cardpopup.js]: FYI: In a subsequent commit I just hardcoded the `utm_source`. (We should still set it manually on each homepage link in case clientside javascript is disabled.)

File: package.json (hunk 2 above)
Comment (NilsEnevoldsen) [reply package.json]: I removed the vanilla tippy.js dependency, although I'm still just using the tippy.js that's itself a dependency of VueTippy. I didn't "vue-ify" my code.

**Comment by NilsEnevoldsen** [comment]
Responded to inline comments individually.

W.r.t other comments:

1. After mouseover but before the image loads, it's impossible to tell there's support for hover images.

Added progress cursor in 9ae81fe.

2. On mobile, the card images can get cut off on the side of the page (left side for me).

For me, at the moment, mobile is so nonfunctional (on iOS) that I can't get them to show. See next item.

3. On mobile it's hard to see the card images or know that we have them, since there's no mouseover.

See https://github.com/NilsEnevoldsen/ScryfallLinks/issues/11. I worked on this last year, but I just don't know how to implement the behavior I want on mobile. Mobile browsers seemed finicky. Help appreciated.

4. Can we precache the card images?

Absolutely, but I don't know how. In fact, on a page like this, we don't need the client to fetch data from Scryfall at all; the appropriate HTML and blobs could all be delivered to the client by the WhatsInStandard server. I don't know how to "preprocess" that, short of requiring the human developer to enter it all manually. There's probably a "node" way to do it?

**Comment by glacials** [comment]
Cool, this is in a good state to merge imo 👍  the part about requiring a human developer to do stuff for precaching is on point. So let's punt on precaching until we have bans in the API, which will make doing it programmatically easier. I can add some runtime caching myself later, that shouldn't block this branch because we never had it with Deckbox previews either, same for my comment about mobile.

If you're curious in general about that stuff, look up service workers. You can actually turn off your internet and still load whatsinstandard.com from a new tab :P 

Thanks for your hard work!

**Comment by tooomm** [comment]
This works very well and looks gooood, thank you @NilsEnevoldsen!
